Adding a docker-compose example for v4 of the grid
SeleniumHQ/docker-selenium pull request #1386
Opened 2021-09-09 09:05 UTC by kewinremy

### Motivation and Context
Developers willing to try out the selenium grid version 4 would like to have an easy way to get started. 

### Description
I just added a yml file with 1 hub & 3 nodes for easing them the start

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-09-09 09:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/docker-selenium?pullRequest=1386) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/docker-selenium?pullRequest=1386) before we can accept your contribution.<br/><hr/>**Kewin Remy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/docker-selenium?pullRequest=1386) it.</sub>

2021-09-09 13:02 UTC, diemol requested changes
Thank you for this PR, @kewinremy!

However, what is the benefit of this file over the one we have in the repo?
https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3.yml

2021-09-10 06:14 UTC, kewinremy commented
Hi @diemol , I do not know well docker-compose and therefore did not understand that the deployment versions correspond to docker-compose and not the selenium-grid. Yes, this pull request does not bring much. We can close it, you are right. Sorry for my mistake. Need to catch up...

2021-09-10 06:15 UTC, closed without merging

2021-09-10 07:28 UTC, diemol commented
No worries, and thank you for clarifying!