Add libnss3-tools installation to chrome and edge image
SeleniumHQ/docker-selenium pull request #1567
Opened 2022-05-09 13:40 UTC by algoritmus

**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Added libnss3-tools package to image in order to be able to add custom certificates, WAs, etc to nssdb, or be able to create new nssdb. Nssdb certificate storage is used by chromium based browsers (Chrome, Edge)

### Motivation and Context
In order to be able to add custom certificates, WAs, etc to nssdb, or be able to create new nssdb. Nssdb certificate storage is used by chromium based browsers (Chrome, Edge)

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-09 13:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/docker-selenium?pullRequest=1567) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/docker-selenium?pullRequest=1567) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/docker-selenium?pullRequest=1567) it.</sub>

2022-05-10 14:01 UTC, diemol requested changes
Changes to Nodes should be applied to this file https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/Dockerfile.txt

2022-05-10 14:22 UTC, algoritmus commented
Corrected

2022-05-10 14:23 UTC, diemol requested changes
Still missing docs showing how to use the feature. Could you please add them to the README?

2022-05-10 14:48 UTC, diemol requested changes

2022-05-10 14:48 UTC, diemol commented on README.md
> +certutil -d sql:$HOME/.pki/nssdb -N
But how would one execute those commands inside the container?

Can you please add a more complete example? I am sure issues will be created asking that.

2022-05-10 14:54 UTC, algoritmus commented
Added usage to readme

2022-05-10 15:20 UTC, algoritmus commented on README.md
> +certutil -d sql:$HOME/.pki/nssdb -N
readme extended with usage

2022-05-11 09:13 UTC, diemol commented on README.md
> +
Apologies if I am being too exhaustive in the review, but if a user needs to create their own image to install the certificates, what is the benefit of installing the tools beforehand?

This PR could be only adding this example to the documentation, and showing how the tools can be installed.

Am I missing something?

2022-05-11 09:14 UTC, diemol commented on README.md
> +
If you want to have a quicker conversation, feel free to drop by our chat [(Matrix, IRC or Slack)](https://www.selenium.dev/support/#ChatRoom), and we can get this done.

2022-05-11 09:28 UTC, algoritmus commented
The point would be that usually companies allows no access to external
repos, so cannot do the install part of the libnss3. It is usually allows
to get docker images but cannot do any apt-get. Ok, frankly speaking here I
am a bit selfish, and this would help me, rather create an image at home
with libnss install then use that image to add certs within enterprise
environment.

Feel free to reject the PR if you think it would serve too narrow user base.

Attila

On Wed, 11 May 2022 at 11:13 Diego Molina ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/SeleniumHQ/docker-selenium/pull/1567#discussion_r870062943>
> :
>
> > +```bash
> +FROM selenium/node-edge:latest
> +
> +USER root
> +
> +COPY certs/ /etc/certs # copy over the certificate file
> +
> +RUN mkdir -p -m755 /home/seluser/.pki/nssdb \ #create nssdb folder
> +    && certutil -d sql:/home/seluser/.pki/nssdb -N --empty-password \ # create new db without password
> +    && certutil -d sql:/home/seluser/.pki/nssdb -A -t "C,," -n companyca -i /etc/certs/companeca.pem \ #trust company CA
> +    && pk12util -d sql:/home/seluser/.pki/nssdb -i client_cert.p12 -W password_of_clent_cert # client certificate install
> +
> +```
> +This way the certificates will be installed and the node will start automatically as before.
> +
> +___
> +
>
> Apologies if I am being too exhaustive in the review, but if a user needs
> to create their own image to install the certificates, what is the benefit
> of installing the tools beforehand?
>
> This PR could be only adding this example to the documentation, and
> showing how the tools can be installed.
>
> Am I missing something?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SeleniumHQ/docker-selenium/pull/1567#pullrequestreview-968960352>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADK3FFYGVHFZTDJREH4H5L3VJN23DANCNFSM5VOJ7VPA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-05-12 14:36 UTC, diemol commented
@algoritmus thanks for being open about it. I am not sure if it is a common use case or not.

These images try to have as few things as possible to cover most use cases. However, I know some people ask every now and then about installing certificates. If you want, I'd be happy to receive a contribution to the README showing how to do it. Would you be OK with that?

2022-05-12 14:39 UTC, algoritmus commented
Sure, no problem.

On Thu, 12 May 2022 at 16:36 Diego Molina ***@***.***> wrote:

> @algoritmus <https://github.com/algoritmus> thanks for being open about
> it. I am not sure if it is a common use case or not.
>
> These images try to have as few things as possible to cover most use
> cases. However, I know some people ask every now and then about installing
> certificates. If you want, I'd be happy to receive a contribution to the
> README showing how to do it. Would you be OK with that?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SeleniumHQ/docker-selenium/pull/1567#issuecomment-1125075243>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADK3FF3EZBWJDIXQY4AVETDVJUJQTANCNFSM5VOJ7VPA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-07 09:58 UTC, closed without merging