[helm] add support of loadBalancerIP for hub and router services
SeleniumHQ/docker-selenium pull request #1589
Opened 2022-06-01 08:02 UTC by germetist

### Description

Templates under  `charts/selenium-grid/templates/hub-service.yaml` and `charts/selenium-grid/templates/router-service.yaml` are updated to support loadBalancerIP value
Values under `charts/selenium-grid/values.yaml` is updated to support loadBalancerIP value
Readme under `charts/selenium-grid/README.md` is updated to describe new values

### Motivation and Context

This PR adds support to the `loadBalancerIP` parameter when the service type is [LoadBalancer](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer). This allows using of a specific IP for some cloud providers and on-premises

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-01 08:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/SeleniumHQ/docker-selenium?pullRequest=1589) <br/>All committers have signed the CLA.

2022-06-15 10:12 UTC, diemol commented
@den-is any chance you could help us to review this PR?

2022-06-16 11:23 UTC, diemol requested changes
Could you please update your fork and also update the values in `Chart.yaml`?

2022-07-03 11:05 UTC, germetist commented
> Could you please update your fork and also update the values in `Chart.yaml`?

Sorry for long answer
Updated from upstream

2022-07-03 11:08 UTC, germetist commented
> Could you please update your fork and also update the values in `Chart.yaml`?

Values in `Chart.yaml` ?
Now is
```
apiVersion: v2
name: selenium-grid
description: A Helm chart for creating a Selenium Grid Server in Kubernetes
type: application
version: 0.6.2
appVersion: 4.3.0-20220628
icon: https://github.com/SeleniumHQ/docker-selenium/raw/trunk/logo.png
```
Do you mean up `version`?

2022-07-07 21:38 UTC, diemol commented
Yes the version and also the CHANGELOG please, so we can do a release after merging.

2022-07-08 06:32 UTC, germetist commented
> Yes the version and also the CHANGELOG please, so we can do a release after merging.

Done

2022-07-12 17:15 UTC, diemol approved these changes
Thank you, @germetist!

Minor changes, but I can do them myself.

2022-07-12 17:15 UTC, diemol commented on charts/selenium-grid/CHANGELOG.md
> +## :heavy_check_mark: 0.7.1
```suggestion
## :heavy_check_mark: 0.8.0
```

2022-07-12 17:15 UTC, diemol commented on charts/selenium-grid/Chart.yaml
> +version: 0.7.1
```suggestion
version: 0.8.0
```

2022-07-12 17:47 UTC, merged