[grid][chart] Allows users to turn off Deployment creation for Nodes
SeleniumHQ/docker-selenium pull request #1709
Opened 2022-10-27 15:45 UTC by mhnaeem

### Description
This change introduces a new value called `deploymentEnabled` for each of the node browsers, if the value is set to `true` Deployments will be created for each of the respective nodes however if `false` no Deployments will be created.

This will allow users to turn off creation of the default deployments and to use other resource types instead such as jobs.

### Motivation and Context

Fixes #1708

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-10-31 13:12 UTC, diemol requested changes
Can you also please update the changelog and the `Chart.yaml` file?

2022-10-31 13:59 UTC, mhnaeem commented
@diemol Can you please take a look at the `Chart.yaml` file again? I couldn't find any instructions on what update was required so I just bumped up the version and added a line in Changelog

2022-10-31 14:28 UTC, diemol approved these changes
That looks, perfect, thank you!

2022-10-31 14:29 UTC, merged

2022-11-16 15:29 UTC, Xcalizorz commented
Sorry for coming in so late, but I don't understand this feature. Why not just use `.Values.chromeNode.enabled` instead of introducing and new variable that does the same?

I also see that this new variable is used with the same logic as `.Values.chromeNode.enabled`.

```yaml
{{- if and .Values.chromeNode.enabled .Values.chromeNode.deploymentEnabled }}
```
Both variables are dependent on each other now? If someone did not want the chrome nodes to be deployed, the would just set `.Values.chromeNode.enabled = false` 

@mhnaeem can you please explain the added value here?

2022-11-16 19:38 UTC, mhnaeem commented
For our use case we needed to use Keda `ScaledObjects` and/or `ScaledJobs` in our workflow and not the default `Deployment` which kept creating extra pods for no reason. The solution was to simply disable the default deployment and use a custom one created by Keda. Even with 0 replicas this `Deployment` item existed in our cluster.

Plus I am hoping that the autoscaling PR #1714 goes out soon which will use `ScaledObjects`. We can then possibly have `scaleobjects.enabled` and `scaledjobs.enabled` values so users can even further configure what type of pods they need instead of being stuck with the default one for autoscaling.

I did not think much of this change because ` .Values.chromeNode.service.enabled` already exists and does about the same thing