replace 777 by 775 and change file owner to seluser
SeleniumHQ/docker-selenium pull request #1963
Opened 2023-10-02 21:13 UTC by eravion

**Thanks for contributing to the Docker-Selenium project!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://selenium.dev/documentation/en/contributing/) guidelines, applied for this repository.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-10-02 21:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeleniumHQ/docker-selenium?pullRequest=1963) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeleniumHQ/docker-selenium?pullRequest=1963) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeleniumHQ/docker-selenium?pullRequest=1963) it.</sub>

2023-10-03 19:37 UTC, diemol commented
Can you explain why this is needed?

2023-10-04 05:50 UTC, eravion commented
Hello @diemol ,
We have security check on docker folder rights, 777 are not allowed by our security dept..
This change fix this issue.
One border effect is managed by https://github.com/SeleniumHQ/docker-selenium/pull/1964

2023-11-17 05:06 UTC, vietnd96 commented
Hi @eravion, may I know your security dept checks this compliance and reports it by which tool?

2023-11-17 13:57 UTC, eravion commented
Hello @vietnd96 
Internal tool, sorry cannot share more.

2023-11-22 09:55 UTC, luisfcorreia commented
This change seems logical to me.
Must investigate if there are any side effects

2023-11-22 18:41 UTC, eravion commented
thanks @luisfcorreia 
Side effect identify during my test fixed by : https://github.com/SeleniumHQ/docker-selenium/pull/1964

2023-11-23 11:23 UTC, diemol requested changes
Can you please check the comments and update your PR with the changes from `trunk`?

2023-11-23 11:23 UTC, diemol commented on Base/Dockerfile
> +RUN chmod 775 /opt/bin/*.sh
Please do the `COPY` with `chmod` as mentioned in the Docker documentation https://docs.docker.com/engine/reference/builder/#copy

2023-11-23 11:23 UTC, diemol commented on Base/Dockerfile
> +  # && chown seluser:seluser /var/run/supervisor /var/log/supervisor /opt/selenium /etc/passwd \
Why are you keeping this commented line?

2023-11-23 11:23 UTC, diemol commented on Base/Dockerfile
> +  && chown seluser:seluser /var/run/supervisor /var/log/supervisor /opt/selenium \
Why did you remove `/etc/passwd`?

2023-12-12 05:00 UTC, vietnd96 commented
Hi @eravion, `777` removal is already considered via PR #2056.
A new image tag will be released soon for your scan.
Thank you!

2023-12-12 10:36 UTC, closed without merging

2023-12-12 10:36 UTC, vietnd96 commented
Please use the new image tag `4.16.1-20231212` for your evaluation.
I will close the PR, feel free to continue the conversation around this feat #2056 or reopen this PR if something else you want to add. Thanks!