Bump images to 4.14.0
SeleniumHQ/docker-selenium pull request #1970
Opened 2023-10-10 07:44 UTC by luisfcorreia

Bump images to 4.14.0

Removed selenium-http-jdk-client-xxx.jar from image as we're now using Java 11

### Description

### Motivation and Context

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] I have read the [contributing](https://selenium.dev/documentation/en/contributing/) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-10-11 04:02 UTC, amardeep2006 commented
I see multiple reference to /opt/selenium/selenium-http-jdk-client.jar in NodeBase/start-selenium-node.sh .
Can that cause some issue on runtime ?
Few references I see : 
https://github.com/SeleniumHQ/docker-selenium/blob/69d9349c6eefcdcaa9b899547caceb86f9f7998d/NodeBase/start-selenium-node.sh#L39C1-L39C10

https://github.com/SeleniumHQ/docker-selenium/blob/69d9349c6eefcdcaa9b899547caceb86f9f7998d/NodeBase/start-selenium-node.sh#L54

2023-10-11 08:40 UTC, luisfcorreia commented
yes @amardeep2006, you may be right, I'll look into it

2023-10-15 22:43 UTC, diemol requested changes

2023-10-15 22:43 UTC, diemol commented on Base/Dockerfile
> +  #  -O /opt/selenium/selenium-http-jdk-client.jar \
Please delete this lines instead of commenting on them.

2023-10-15 22:43 UTC, diemol commented on charts/selenium-grid/CHANGELOG.md
> +
This should be `0.22.1`.

2023-10-15 22:43 UTC, diemol commented on charts/selenium-grid/Chart.yaml
> +version: 0.23.0
This should be `0.22.1`.

2023-10-16 07:09 UTC, luisfcorreia commented
Proposed changes applied

2023-10-16 07:23 UTC, baflQA commented
Btw, there is already a newer version of Selenium - [4.14.1]

2023-10-16 07:27 UTC, luisfcorreia commented
Forgot there is a new Selenium Java release in the meantime (thanks Bartek)

2023-10-16 10:52 UTC, diemol requested changes

2023-10-16 10:52 UTC, diemol commented on charts/selenium-grid/CHANGELOG.md
> +- Update image tag to 4.14.0-20231010
I was thinking about this again; this file cannot be changed before the release happens. Can you please revert this change and send it in a separate PR?

2023-10-16 10:52 UTC, diemol commented on charts/selenium-grid/Chart.yaml
> +version: 0.22.1
I was thinking about this again; this file cannot be changed before the release happens. Can you please revert this change and send it in a separate PR?

2023-10-16 11:54 UTC, luisfcorreia commented
Reverting as requested

2023-10-16 12:52 UTC, diemol approved these changes
Let's wait for CI to pass and then let's merge.

2023-10-16 13:20 UTC, merged